### ISSUE TITLE
Is the naming convention tool from Ryan & Jan opensource

### ISSUE THREAD

**Issue by irwins** [psconfeu/2022#35]
There's a demo.ps1 available but that's about it... Just wondering

**Comment by gaelcolas** [comment]
Will ping Ryan for you ;)

**Comment by rdbartram** [comment]
Hi @irwins 
sorry i completely missed this comment. 

here is the repo https://github.com/worxspace/PSCAFNaming

and yes its open source

**Comment by gaelcolas** [comment]
Hope the link is in your pres, otherwise consider adding an .md with the info.
Thanks @rdbartram, closing this issue.
