### ISSUE TITLE
Thomas Maurer - Mastering Azure using Cloud Shell, PowerShell and Bash!

### ISSUE THREAD

**Issue by m-hanisch** [psconfeu/2022#36]
Hi
I could not find the session by Thomas Maurer *Mastering Azure using Cloud Shell, PowerShell and Bash!*
Tuesday 11:00 AM 45 min Track 1

May I just wait for the session recording. Any update regarding recording release date?

**Comment by gaelcolas** [comment]
Good point, let me ping him!

**Comment by m-hanisch** [comment]
@gaelcolas 
Thank you for your efforts 👍 
Currently, watching the recording of [How To Create Great Tech Demos And Presentations - Thomas Maurer - PSConfEU 2022](https://youtu.be/Sf-S4rdQ3Gc) - also presented by Thomas Maurer.
In the recording at [28:40](https://youtu.be/Sf-S4rdQ3Gc?t=1720), Thomas Maurer provided the link to his related blog post on that topic: [https://aka.ms/TechDemos](https://aka.ms/TechDemos)
May add that, too?

Any update?

**Comment by gaelcolas** [comment]
I've tried Twitter and Teams, no luck so far.

**Comment by thomasmaurer** [comment]
Hi everyone. Sorry for the late response,

Recording for Mastering Azure using Cloud Shell, PowerShell and Bash! can be found here: https://www.youtube.com/watch?v=5wZcUzEk4WY

**Comment by gaelcolas** [comment]
Thanks
Closing since @thomasmaurer added his slides and sessiosn here https://github.com/psconfeu/2022/tree/main/ThomasMaurer/MasteringAzurewithCloudShellPowerShellandBash
Please re-open if you think something is missing.
